#! /usr/bin/perl -w
use strict;

open IFILE, $ARGV[0] or die;

open OFILE, ">sigs-list.c" or die;
print OFILE "/* Automatically generated by make-sigs-list.pl */\n";

while (<IFILE>) {
	chop;
	next unless /_get_type\s*$/;
	next if /win32/;
	print OFILE "\tt = $_();\n";
}

close IFILE;
close OFILE;

