
MODULE	:=glib
SRC	:=override channel callback
include script/Makefile.common

$(ODIR)override.$O: $(IDIR)/override.c $(DEP)
$(ODIR)callback.$O: $(IDIR)/callback.c $(DEP)
$(ODIR)channel.$O: $(IDIR)/channel.c $(DEP)

